typeScore: ['Futbol', 'Futbol_Sala', 'Hoquei', 'Hoquei_Gel', 'Basquet', 'Handball', 'Rugby', 'Futbol_America', 'Formula1', 'MotoGP', 'Moto2', 'Moto3', 'Sorteig_Champions', 'Golejador']

Futbol: [0,1,2,3,4,5,6,7,8,9,10,11,12]

Futbol_Sala: [0,1,2,3,4,5,6,7,8,9,10,11,12]

Hoquei: [0,1,2,3,4,5,6,7,8,9,10,11,12]

Hoquei_Gel: [0,1,2,3,4,5,6,7,8,9,10,11,12]

Basquet: [-30,-29,-28,-27,-26,-25,-24,-23,-22,-21,-20,-19,-18,-17,-16,-15,-14,-13,-12,-11,-10,-9,-8,-7,-6,-5,-4,-3,-2,-1,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30]

Handball: [-20,-19,-18,-17,-16,-15,-14,-13,-12,-11,-10,-9,-8,-7,-6,-5,-4,-3,-2,-1,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]

Rugby: [-20,-19,-18,-17,-16,-15,-14,-13,-12,-11,-10,-9,-8,-7,-6,-5,-4,-3,-2,-1,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]

Futbol_America: [-20,-19,-18,-17,-16,-15,-14,-13,-12,-11,-10,-9,-8,-7,-6,-5,-4,-3,-2,-1,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]

Formula1: ['Vettel','Webber','Hamilton','Rosberg','Alonso','Massa','Raikonnen','Grosjean','Button','Di Resta','Sutil','Perez','Vergne','Ricciardo','Hulkenberg','Maldonado','Bottas','Gutierrez','Bianchi','Pic','Van der Garde','Chilton']

MotoGP: ['Marquez','Pedrosa','Lorenzo','Rossi','Dovizioso','Hayden','Edwards','Bradl','Aoyama','Barbera','Petrucci','Spies','De Puniet','Abraham','Bautista','Iannone','Crutchlow','Smith','Espargaro','Pesek','Staring','Hernandez','Laverti','Corti']

Moto2: ['Redding','Espargaro','Rabat','Aegerter','Kallio','Zarco','Nakagami','Torres','Terol','Corsi','Simeon','Luthi','De Angelis','Simon','West','Pasini']

Moto3: ['Rins','Marquez','Vinales','Folguer','Salom','Sissis','Khairuddin','Oliveira','Fenati','Kornfeil','Ajo','Masbou','Techer','Loi','Ferrari','Antonelli']

Sorteig_Champions: ['--Bombo2','Shaktar','Milan','Schalke','O.Marsella','CSKA','PSG','Juventus','--Bombo3','Zenit','Man City','Ajax','B.Dortmund','Basilea','Olympiacos','Galatasaray','B.Leverkusen','--Bombo4','Copenhague','Napoli','Anderlecht','Celtic','S.Bucarest','Viktoria Plzen','Austria Viena']

Golejador: ['Messi','Neymar','Alexis','Pedro','Cesc','Xavi','Iniesta','Busquets','Alves','Puyol','Pique','Mascherano','Bartra','Adriano','Cristina','Benzema','Bale','Di Maria','Morata','Isco','Kedhira','Illara','Modric','Ramos','Pepe','Varane','Carvajal','Marcelo','Arbeloa']

Ronda_Champions: ['Bayer 04 Leverkusen', 'Galatasaray AŞ', 'Olympiacos FC', 'Manchester City FC', 'FC Schalke 04', 'Arsenal FC', 'FC Zenit', 'AC Milan']
